# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\repositories\private\LabelmeDIY\labelme\ui\tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(255, 70)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.cutout = QtWidgets.QPushButton(Form)
        self.cutout.setObjectName("cutout")
        self.gridLayout.addWidget(self.cutout, 1, 2, 1, 1)
        self.classify = QtWidgets.QPushButton(Form)
        self.classify.setObjectName("classify")
        self.gridLayout.addWidget(self.classify, 0, 2, 1, 1)
        self.unlabeled = QtWidgets.QPushButton(Form)
        self.unlabeled.setObjectName("unlabeled")
        self.gridLayout.addWidget(self.unlabeled, 0, 1, 1, 1)
        self.rename = QtWidgets.QPushButton(Form)
        self.rename.setObjectName("rename")
        self.gridLayout.addWidget(self.rename, 1, 0, 1, 1)
        self.filter = QtWidgets.QPushButton(Form)
        self.filter.setObjectName("filter")
        self.gridLayout.addWidget(self.filter, 1, 1, 1, 1)
        self.labeled = QtWidgets.QPushButton(Form)
        self.labeled.setObjectName("labeled")
        self.gridLayout.addWidget(self.labeled, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cutout.setText(_translate("Form", "Cutout"))
        self.classify.setText(_translate("Form", "Classify"))
        self.unlabeled.setText(_translate("Form", "Unlabeled"))
        self.rename.setText(_translate("Form", "Rename"))
        self.filter.setText(_translate("Form", "Filter"))
        self.labeled.setText(_translate("Form", "Labeled"))
